"""cefr

Revision ID: f9f54b35b20d
Revises: 9f4d87f1c78d
Create Date: 2025-05-28 14:54:01.950283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'f9f54b35b20d'
down_revision: Union[str, None] = '9f4d87f1c78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cefr = ENUM('A', 'B', 'C', name='cefr')
    cefr.create(op.get_bind())
    op.add_column('users', sa.Column('cefr', sa.Enum('A', 'B', 'C', name='cefr'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cefr = ENUM('A', 'B', 'C', name='cefr')
    cefr.drop(op.get_bind())
    op.drop_column('users', 'cefr')
    # ### end Alembic commands ###
